### PR TITLE
Created Button Group component

### PR DESCRIPTION
**Pull request by AbhimanyuRaut**

### CODE REVIEW

**Comment by adamcoard-maximus** [comment]
Hi Abhi,

I really, *really* like this PR, how you've coded everything to be consistent with the library. The code is clean and easy to follow, there are well-written tests, and it auto-adds to the module. This is exactly what I was hoping for and I'm really impressed.  

There's only one thing I'd request. Please implement ControlValueAccessor on the class, using NG_VALUE_ACCESSOR. This will make the component compatible with Reactive forms. Take a look at DropdownComponent (simple), DatepickerComponent (middle),  AddressComponent(complex) for implementations across 3 different components. Datepicker is probably the best one. 

Here's a short blog on the topic: https://alligator.io/angular/custom-form-control/

Once you have that done this PR looks good and you'll be good to submit additional PRs for your other components.

Thanks.

**Comment by AbhimanyuRaut** [comment]
Thanks for the feedback Adam! I have implemented the ControlValueAccessor interface and added the example snippet.

**Comment by adamcoard-maximus** [comment]
I see you've implemented ControlValueAccessor which is good, but I see a couple potential bugs in the component:

1. The template calls `setButtonGrpVal()`, but this method is missing in the TypeScript
2. There's a method called `focus()` which is not invoked anywhere from what I can see.
3. `registerOnTouched(), registerOnChange()`, are not called anywhere.

Regarding #3 - If for example `setButtonGrpVal()` existed and updated `this.data` then we'd want to call `this._onChanged()` there because the value has changed and now we want to register it with Angular. Likewise,  if `focus()` was in use we'd probably want to call `this._onChange()` in there to register the that change with angular.

**Comment by adamcoard-maximus** [comment]
Great Abhi! Thanks for making all those changes. Approved.

**Comment by AbhimanyuRaut** [comment]
Thanks Adam!

**Pull request merged**
